### ISSUE TITLE
CAT_STATEMENT_TABLE_FULL when listing all users

### ISSUE THREAD

**Issue by hurngchunlee** [cyverse/go-irodsclient#30]
Hello,

First of all, thanks for this pure Golang implementation of the iRODS protocol.  Although it seem to me that this package is still heavily under development, I am already trying to use it for a project.

I just want to report an error I run into.  When I use the `fs.ListUsers(*conn)` function to get a list of iRODS users, I get the error `CAT_STATEMENT_TABLE_FULL`.

After checking the source code, the issue seems to be due to the fact that the value of `continueIndex` is not used in the line below (i.e. the second argument of the function `message.NewIRODSMessageQueryRequest` is `0` instead of `continueIndex` changed in the iteration):

https://github.com/cyverse/go-irodsclient/blob/bf359d5f171e080a9ca6beac240bef0a6802dd8a/irods/fs/usergroup.go#L325

**Comment by iychoi** [comment]
Thanks for the bug report. I changed the code at `v0.11.0` release.
