### ISSUE TITLE
is fs.FileSystem thread safe?

### ISSUE THREAD

**Issue by hurngchunlee** [cyverse/go-irodsclient#37]
Hello,

I am using go routines to implement concurrent file upload/download to iRODS.  I wonder if the `fs.FileSystem` is thread safe so that I just need to create it once and shared across go routines?  Thanks!

**Comment by iychoi** [comment]
Yes, fs.FileSystem must be thread safe. If it is not, it is a bug.

You can check `gocommands` source code to see how I use fs.FileSystem for parallel data transfer. 
For download (get),
https://github.com/cyverse/gocommands/blob/main/cmd/subcmd/get.go

For upload (put),
https://github.com/cyverse/gocommands/blob/main/cmd/subcmd/put.go

**Comment by hurngchunlee** [comment]
Thanks @iychoi for the answer and the examples.  One more question, is the server-side checksum calculation (i.e. the `-k` option of `iput`) already supported?  Thanks again.

**Comment by iychoi** [comment]
I'm not sure how `-k` option works in iCommands internally. If it simply gets checksum already calculated and compares with local one, you can implement the same thing by yourself. The `ls` command in `gocommands` gets checksum and displays it. 

If iCommands makes iRODS to caclulate a new checksum with the `-k` flag, it's not yet implemented in `gocommands` and `go-irodsclient`. 
I'll need to take a look in the future.

**Comment by trel** [comment]
yes, for iCommands `iput`...

```
 -k  checksum - calculate a checksum on the data server-side, and store
       it in the catalog.
 -K  verify checksum - calculate and verify the checksum on the data, both
       client-side and server-side, and store it in the catalog.
```

**Comment by iychoi** [comment]
I think this can work for the purpose. It's not exposed via `fs.FileSystem`, but you can call it after getting a connection from the `fs.FileSystem` with `GetMetadataConnection()`.

https://github.com/cyverse/go-irodsclient/blob/main/irods/fs/checksum.go#L12

**Comment by hurngchunlee** [comment]
> I think this can work for the purpose. It's not exposed via `fs.FileSystem`, but you can call it after getting a connection from the `fs.FileSystem` with `GetMetadataConnection()`.
> 
> https://github.com/cyverse/go-irodsclient/blob/main/irods/fs/checksum.go#L12

Thanks!  It works like a charm!!

**Comment by iychoi** [comment]
Great to hear that!
